//
//  Workspace.swift
//  AppManifests
//
//  Created by 이정원 on 6/1/25.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: ProjectInfo.appName,
    projects: ["Projects/**"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
