import SwiftUI

public extension Image {
    private init(_ name: String) {
        self.init(name, bundle: Bundle.module)
    }
    
    static let iconArrowLeft = Self("icon_arrow_left")
    static let iconArtistPlaceholder = Self("icon_artist_placeholder")
    static let iconArtistPlaceholderSelected = Self("icon_artist_placeholder_selected")
    static let iconBell = Self("icon_bell")
    static let iconBus = Self("icon_bus")
    static let iconCalendar = Self("icon_calendar")
    static let iconCalendarMode = Self("icon_calendar_mode")
    static let iconChecked = Self("icon_checked")
    static let iconChevronLeft = Self("icon_chevron_left")
    static let iconChevronRight = Self("icon_chevron_right")
    static let iconClose = Self("icon_close")
    static let iconDown = Self("icon_down")
    static let iconDownload = Self("icon_download")
    static let iconFilter = Self("icon_filter")
    static let iconGridMode = Self("icon_grid_mode")
    static let iconHeart = Self("icon_heart")
    static let iconHeartFill = Self("icon_heart_fill")
    static let iconHome = Self("icon_home")
    static let iconInstagram = Self("icon_instagram")
    static let iconLink = Self("icon_link")
    static let iconList = Self("icon_list")
    static let iconMyPage = Self("icon_my_page")
    static let iconNotification = Self("icon_notification")
    static let iconNotificationFill = Self("icon_notification_fill")
    static let iconPetalBackground = Self("icon_petal_background")
    static let iconPicture = Self("icon_picture")
    static let iconPlus = Self("icon_plus")
    static let iconSelectedDay = Self("icon_selectedDay")
    static let iconSubway = Self("icon_subway")
    static let iconTimetable = Self("icon_timetable")
    static let iconTriangle = Self("icon_triangle")
    static let iconUnchecked = Self("icon_unchecked")
    static let iconWebsite = Self("icon_website")
    static let sampleFestival = Self("sample_festival")
}
