import UIKit
import SwiftUI

public extension Image {
    private init(_ name: String) {
        self.init(name, bundle: Bundle.module)
    }
    
    static let iconArrowLeft = Self("icon_arrow_left")
    static let iconArtistPlaceholder = Self("icon_artist_placeholder")
    static let iconArtistPlaceholderSelected = Self("icon_artist_placeholder_selected")
    static let iconBell = Self("icon_bell")
    static let iconBellGray = Self("icon_bell_gray")
    static let iconBus = Self("icon_bus")
    static let iconCalendar = Self("icon_calendar")
    static let iconCalendarMode = Self("icon_calendar_mode")
    static let iconChecked = Self("icon_checked")
    static let iconChevronLeft = Self("icon_chevron_left")
    static let iconChevronRight = Self("icon_chevron_right")
    static let iconClose = Self("icon_close")
    static let iconDown = Self("icon_down")
    static let iconDownload = Self("icon_download")
    static let iconError = Self("icon_error")
    static let iconFilter = Self("icon_filter")
    static let iconGridMode = Self("icon_grid_mode")
    static let iconHeart = Self("icon_heart")
    static let iconHeartFill = Self("icon_heart_fill")
    static let iconHeartGray = Self("icon_heart_gray")
    static let iconHome = Self("icon_home")
    static let iconInstagram = Self("icon_instagram")
    static let iconLink = Self("icon_link")
    static let iconList = Self("icon_list")
    static let iconMyPage = Self("icon_my_page")
    static let iconNotification = Self("icon_notification")
    static let iconNotificationFill = Self("icon_notification_fill")
    static let iconPetalBackground = Self("icon_petal_background")
    static let iconPicture = Self("icon_picture")
    static let iconPlus = Self("icon_plus")
    static let iconSelectedDay = Self("icon_selectedDay")
    static let iconShare = Self("icon_share")
    static let iconStarGrey = Self("icon_star_grey")
    static let iconSubway = Self("icon_subway")
    static let iconTimetable = Self("icon_timetable")
    static let iconTriangle = Self("icon_triangle")
    static let iconUnchecked = Self("icon_unchecked")
    static let iconWebsite = Self("icon_website")
    static let logo = Self("logo")
    static let logoSplash = Self("logo_splash")
    static let placeholder1 = Self("placeholder1")
    static let placeholder2 = Self("placeholder2")
    static let placeholder3 = Self("placeholder3")
    static let sampleFestival = Self("sample_festival")
    static let star = Self("star")
}

public extension UIImage {
    static func named(_ name: String) -> UIImage {
        return UIImage(named: name, in: Bundle.module, compatibleWith: nil) ?? UIImage()
    }
    
    static let iconArrowLeft = UIImage.named("icon_arrow_left")
    static let iconArtistPlaceholder = UIImage.named("icon_artist_placeholder")
    static let iconArtistPlaceholderSelected = UIImage.named("icon_artist_placeholder_selected")
    static let iconBell = UIImage.named("icon_bell")
    static let iconBellGray = UIImage.named("icon_bell_gray")
    static let iconBus = UIImage.named("icon_bus")
    static let iconCalendar = UIImage.named("icon_calendar")
    static let iconCalendarMode = UIImage.named("icon_calendar_mode")
    static let iconChecked = UIImage.named("icon_checked")
    static let iconChevronLeft = UIImage.named("icon_chevron_left")
    static let iconChevronRight = UIImage.named("icon_chevron_right")
    static let iconClose = UIImage.named("icon_close")
    static let iconDown = UIImage.named("icon_down")
    static let iconDownload = UIImage.named("icon_download")
    static let iconError = UIImage.named("icon_error")
    static let iconFilter = UIImage.named("icon_filter")
    static let iconGridMode = UIImage.named("icon_grid_mode")
    static let iconHeart = UIImage.named("icon_heart")
    static let iconHeartFill = UIImage.named("icon_heart_fill")
    static let iconHeartGray = UIImage.named("icon_heart_gray")
    static let iconHome = UIImage.named("icon_home")
    static let iconInstagram = UIImage.named("icon_instagram")
    static let iconLink = UIImage.named("icon_link")
    static let iconList = UIImage.named("icon_list")
    static let iconMyPage = UIImage.named("icon_my_page")
    static let iconNotification = UIImage.named("icon_notification")
    static let iconNotificationFill = UIImage.named("icon_notification_fill")
    static let iconPetalBackground = UIImage.named("icon_petal_background")
    static let iconPicture = UIImage.named("icon_picture")
    static let iconPlus = UIImage.named("icon_plus")
    static let iconSelectedDay = UIImage.named("icon_selectedDay")
    static let iconShare = UIImage.named("icon_share")
    static let iconStarGrey = UIImage.named("icon_star_grey")
    static let iconSubway = UIImage.named("icon_subway")
    static let iconTimetable = UIImage.named("icon_timetable")
    static let iconTriangle = UIImage.named("icon_triangle")
    static let iconUnchecked = UIImage.named("icon_unchecked")
    static let iconWebsite = UIImage.named("icon_website")
    static let logo = UIImage.named("logo")
    static let logoSplash = UIImage.named("logo_splash")
    static let placeholder1 = UIImage.named("placeholder1")
    static let placeholder2 = UIImage.named("placeholder2")
    static let placeholder3 = UIImage.named("placeholder3")
    static let sampleFestival = UIImage.named("sample_festival")
    static let star = UIImage.named("star")
}
